### ISSUE TITLE
获取http://localhost:8080/starter.zip压缩包报错

### ISSUE THREAD

**Issue by zhaoye123** [studeyang/start-parent#1]
![image](https://user-images.githubusercontent.com/40014324/206439973-bc24901f-3c94-4127-9deb-0d6dfe31cebe.png)

**Comment by studeyang** [comment]
你的请求参数是什么？正常的参数格式是：

分层架构：
{
    "dependencies": [ ], 
    "name": "Example", 
    "type": "maven-project", 
    "description": "Example project for Spring Boot", 
    "groupId": "com.yourcompany", 
    "artifactId": "example", 
    "version": "1.0.0-SNAPSHOT", 
    "bootVersion": "1.4.2.RELEASE", 
    "packaging": "jar", 
    "applicationName": null, 
    "language": "java", 
    "packageName": "com.yourcompany.example", 
    "javaVersion": "1.8", 
    "baseDir": "example", 
    "parameters": {
        "cookie": "JSESSIONID=4A34F92D60BAB46DB23E95213598C039", 
        "accept-language": "zh-CN,zh;q=0.9", 
        "accept-encoding": "gzip, deflate, br", 
        "referer": "http://localhost:8080/", 
        "sec-fetch-dest": "empty", 
        "sec-fetch-mode": "cors", 
        "sec-fetch-site": "same-origin", 
        "accept": "*/*", 
        "sec-ch-ua-platform": "\"macOS\"", 
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36", 
        "sec-ch-ua-mobile": "?0", 
        "sec-ch-ua": "\"Not?A_Brand\";v=\"8\", \"Chromium\";v=\"108\", \"Google Chrome\";v=\"108\"", 
        "connection": "close", 
        "host": "localhost:8080"
    }
}

None：
{
    "dependencies": [ ], 
    "name": "Example", 
    "type": "based-project", 
    "description": "Example project for Spring Boot", 
    "groupId": "com.yourcompany", 
    "artifactId": "example", 
    "version": "1.0.0-SNAPSHOT", 
    "bootVersion": "1.4.2.RELEASE", 
    "packaging": "jar", 
    "applicationName": null, 
    "language": "java", 
    "packageName": "com.yourcompany.example", 
    "javaVersion": "1.8", 
    "baseDir": "example", 
    "parameters": {
        "cookie": "JSESSIONID=4A34F92D60BAB46DB23E95213598C039", 
        "accept-language": "zh-CN,zh;q=0.9", 
        "accept-encoding": "gzip, deflate, br", 
        "referer": "http://localhost:8080/", 
        "sec-fetch-dest": "empty", 
        "sec-fetch-mode": "cors", 
        "sec-fetch-site": "same-origin", 
        "accept": "*/*", 
        "sec-ch-ua-platform": "\"macOS\"", 
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36", 
        "sec-ch-ua-mobile": "?0", 
        "sec-ch-ua": "\"Not?A_Brand\";v=\"8\", \"Chromium\";v=\"108\", \"Google Chrome\";v=\"108\"", 
        "connection": "close", 
        "host": "localhost:8080"
    }
}

**Comment by zhaoye123** [comment]
![image](https://user-images.githubusercontent.com/40014324/206821074-5c97453f-c3eb-4936-95c2-50a45bca7b4c.png)
你是请求路径里面参数我之前用得原生调用http://localhost:8080/starter.zip

**Comment by studeyang** [comment]
这是一个正常的HTTP请求：
