### ISSUE TITLE
遇到yarn无法下载的问题

### ISSUE THREAD

**Issue by JerryX** [studeyang/start-parent#2]
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.0:install-node-and-yarn (install node and yarn) on project start-client: Could not download Yarn: Could not download https://github.com/yarnpkg/yarn/releases/download/v1.22.4/yarn-v1.22.4.tar.gz: Remote host terminated the handshake: SSL peer shut down incorrectly -> [Help 1]

这个是怎么解决的

**Comment by studeyang** [comment]
这个问题看起来像是你本机网络的原因，尝试在浏览器中打开：https://github.com/yarnpkg/yarn/releases/download/v1.22.4/yarn-v1.22.4.tar.gz

或者你可以手动安装 Yarn，官网：https://yarnpkg.com/en/docs/install

安装Yarn后，可以通过将以下内容添加到你的pom.xml文件中，配置 frontend-maven-plugin 使用你本地的 Yarn 安装：

```xml
<configuration>
  <yarnVersion>1.22.5</yarnVersion>
  <nodeVersion>v14.17.0</nodeVersion>
  <npmVersion>6.14.13</npmVersion>
  <installDirectory>target</installDirectory>
  <workingDirectory>${project.basedir}/src/main/resources/static/</workingDirectory>
</configuration>
```

**Comment by studeyang** [comment]
> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.0:install-node-and-yarn (install node and yarn) on project start-client: Could not download Yarn: Could not download https://github.com/yarnpkg/yarn/releases/download/v1.22.4/yarn-v1.22.4.tar.gz: Remote host terminated the handshake: SSL peer shut down incorrectly -> [Help 1]
> 
> 这个是怎么解决的

这个问题看起来像是你本机网络的原因，尝试在浏览器中打开：https://github.com/yarnpkg/yarn/releases/download/v1.22.4/yarn-v1.22.4.tar.gz

或者你可以手动安装 Yarn，官网：https://yarnpkg.com/en/docs/install

安装Yarn后，可以通过将以下内容添加到你的pom.xml文件中，配置 frontend-maven-plugin 使用你本地的 Yarn 安装：

```xml
<configuration>
  <yarnVersion>1.22.5</yarnVersion>
  <nodeVersion>v14.17.0</nodeVersion>
  <npmVersion>6.14.13</npmVersion>
  <installDirectory>target</installDirectory>
  <workingDirectory>${project.basedir}/src/main/resources/static/</workingDirectory>
</configuration>
```
