### ISSUE TITLE
无法找到对应的依赖

### ISSUE THREAD

**Issue by H-TWINKLE** [studeyang/start-parent#3]
未解析的依赖项: 'io.spring.initializr:initializr-generator:jar:0.20.0-SNAPSHOT'
未解析的依赖项: 'io.spring.initializr:initializr-generator-spring:jar:0.20.0-SNAPSHOT'

**Comment by studeyang** [comment]
你切换到 tag 0.0.2

**Comment by H-TWINKLE** [comment]
> 你切换到 tag 0.0.2

收到，谢谢
